
#ifdef FORTRAN_MODULE
#define FORTRAN_MANGLE_MOD(FORTRAN_MODULE) FORTRAN_MODULE 
// #define FORTRAN_MANGLE(PARAM) __##FORTRAN_MANGLE_MOD(FORTRAN_MODULE)##_MOD_##PARAM
#define FORTRAN_MANGLE(PARAM) __ ## FORTRAN_MODULE
#else
#define FORTRAN_MANGLE(PARAM) PARAM
#endif

